# Generated by Django 4.0.1 on 2022-01-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('video_name', models.CharField(max_length=100)),
                ('video_category', models.CharField(max_length=50)),
            ],
        ),
    ]
