# Generated by Django 4.0.1 on 2022-02-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0003_videolocations_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_item', models.FileField(upload_to='%Y%m%d')),
            ],
        ),
    ]
