# Generated by Django 4.0.1 on 2022-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0005_videofileupload_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofileupload',
            name='converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videofileupload',
            name='file_item',
            field=models.FileField(upload_to='%Y%m%d%H%M%S%f'),
        ),
    ]
