# Generated by Django 6.0.6 on 2026-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0007_videofileupload_is_public_videofileupload_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolocations',
            name='subtitle_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
